#!/bin/bash

if [ `git rev-parse --abbrev-ref HEAD` != "master" ]; then
  echo "Not on master"
  exit 1
fi

test -z "$(git status --porcelain)"
if [ $? != 0 ]; then
  echo "Repo not clean"
  exit 1
fi

gulpur build \
  && REV=`git rev-parse HEAD` \
  && cd ../../cloud-launcher.github.io \
  && git rm -r * \
  && cp -r -v ../www/frontend/.dist/* ./ \
  && echo "www.cloud-launcher.io" > CNAME \
  && git add . --all \
  && git commit -m "Publishing $REV" \
  && git push origin master \
  && echo "Published!" \
|| echo "Something failed. Figure it out!"